version: "3"
services:

  db:
    image: postgres:14
    container_name: db
    volumes:
        - ./backup_data/db:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    expose: 
      - "5432"

  backend:
    restart: always
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./backend:/app
    depends_on:
      - db
  
  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    restart: on-failure
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
  
  # nginx_backend_server:
  #   build: ./nginx_backend_server
  #   container_name: nginx
  #   ports:
  #       - 8000:8000
  #   depends_on:
  #       - backend